name: HoundDog.ai Scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: hounddogai/scanner:staging
    # Skip pull requests created by dependabot
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@master
      - run: hounddog scan
