name: HoundDog.ai Scan
on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: hounddogai/scanner:staging
    steps:
      - uses: actions/checkout@master
      - run: hounddog scan
