name: HoundDog.ai

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  hounddog:
    name: Run HoundDog.ai scan
    runs-on: ubuntu-latest
    container:
      image: hounddogai/scanner:staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run HoundDog.ai scan
        run: >
          hounddog scan
          --output-format=sarif
          --output-filename=results.sarif
          --skip-folder=tests
          --severity=critical
          --severity=high
          --severity=medium
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
